### ISSUE TITLE
Tracer, specifically `OBIO` connections with MOM5

### ISSUE THREAD

**Issue by sanAkel** [GEOS-ESM/GEOS_OceanGridComp#17]
### **Why**? To explore the steps that are needed to implement similar with MOM6.

cc: @mfmehari, @yvikhlya 

- [GEOS_OgcmGridComp.F90](https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/develop/GEOSogcm_GridComp/GEOS_OgcmGridComp.F90) [`Connects `TR` bundle with OBIO`](https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/b5ab7e3ad1d73c0513aae9593b79e7e55b94f64c/GEOSogcm_GridComp/GEOS_OgcmGridComp.F90#L1297-L1309)
 
- [GEOS_OceanGridComp.F90](https://github.com/GEOS-ESM/GEOS_OceanGridComp/blob/develop/GEOS_OceanGridComp.F90)
`TR` and `TRFLUX` are imported to MOM (=MOM5) https://github.com/GEOS-ESM/GEOS_OceanGridComp/blob/f69b49a13261af0f3c469af287f7309fdc8ee627/GEOS_Ocean_StateSpecs.rc#L21-L22

@mfmehari: **What is `TRFLUX`**? See ⬇️ 

- [MOM_GEOS5PlugMod.F90](https://github.com/GEOS-ESM/GEOS_OceanGridComp/blob/develop/MOM_GEOS5PlugMod/MOM_GEOS5PlugMod.F90) `Declare TR as Import`

   - https://github.com/GEOS-ESM/GEOS_OceanGridComp/blob/f69b49a13261af0f3c469af287f7309fdc8ee627/MOM_GEOS5PlugMod/MOM_GEOS5PlugMod_StateSpecs.rc#L32

  - https://github.com/GEOS-ESM/GEOS_OceanGridComp/blob/f69b49a13261af0f3c469af287f7309fdc8ee627/MOM_GEOS5PlugMod/MOM_GEOS5PlugMod.F90#L645
  - https://github.com/GEOS-ESM/GEOS_OceanGridComp/blob/f69b49a13261af0f3c469af287f7309fdc8ee627/MOM_GEOS5PlugMod/MOM_GEOS5PlugMod.F90#L695-L698

  - `Get `TR` from bundle, _put_ it in MOM's state:` https://github.com/GEOS-ESM/GEOS_OceanGridComp/blob/f69b49a13261af0f3c469af287f7309fdc8ee627/MOM_GEOS5PlugMod/MOM_GEOS5PlugMod.F90#L919-L942

  - `Get `TR` from bundle, _get_ it from MOM's state:` https://github.com/GEOS-ESM/GEOS_OceanGridComp/blob/f69b49a13261af0f3c469af287f7309fdc8ee627/MOM_GEOS5PlugMod/MOM_GEOS5PlugMod.F90#L950-L971
 
- `In MOM5 work with`: https://github.com/GEOS-ESM/GEOS_OceanGridComp/blob/f69b49a13261af0f3c469af287f7309fdc8ee627/MOM_GEOS5PlugMod/MOM_GEOS5PlugMod.F90#L64-L65 that are accessed from [ocean_model.F90](https://github.com/GEOS-ESM/MOM5/blob/d5fb80f42f915a8bddba71f9c1315a6e05c03b95/src/mom5/ocean_core/ocean_model.F90#L572-L576)
 

@mfmehari: **Why only `TR` shows up, where is `TRFLUX`**?

**Comment by mfmehari** [comment]
Hi Santha,

I have been working with the CVS S2Sv3 model (with OBIO on).


I don’t see the import TRFLUX used in this model.

It is commented out in /discover/nobackup/mmehari/yuri-s2s3/GEOSodas/src/GEOSgcs_GridComp/GEOSgcm_GridComp/GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/GuestOcean_GridComp.F90

Thank you,
Michael

From: Santha Akella ***@***.***>
Reply-To: GEOS-ESM/GEOS_OceanGridComp ***@***.***>
Date: Monday, January 9, 2023 at 1:50 PM
To: GEOS-ESM/GEOS_OceanGridComp ***@***.***>
Cc: "Mehari, Michael F. (GSFC-610.1)[SCIENCE APPLICATION INTL CORP]" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] [GEOS-ESM/GEOS_OceanGridComp] Tracer, specifically `OBIO` connections with MOM5 (Issue #17)

This issue documents connectivity of tracers from OBIO with MOM5 ocean model in GEOS.
Why? To explore the steps that are needed to implement similar with MOM6.

cc: @mfmehari<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmfmehari&data=05%7C01%7Cmichael.f.mehari%40nasa.gov%7C5cc86d1dd68c4f31758b08daf272660f%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638088870396166760%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9U8eA1kQ9VqV0ZZR%2BYRVlUtIm4eeq1PA7UNWbfEST5I%3D&reserved=0>, @yvikhlya<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fyvikhlya&data=05%7C01%7Cmichael.f.mehari%40nasa.gov%7C5cc86d1dd68c4f31758b08daf272660f%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638088870396166760%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HMvXoCb89IUiBtaYXQBgqZ3FTQtROV0VCxQ1T2dNUfU%3D&reserved=0>

  *   GEOS_OgcmGridComp.F90<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGEOS-ESM%2FGEOSgcm_GridComp%2Fblob%2Fdevelop%2FGEOSogcm_GridComp%2FGEOS_OgcmGridComp.F90&data=05%7C01%7Cmichael.f.mehari%40nasa.gov%7C5cc86d1dd68c4f31758b08daf272660f%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638088870396166760%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=22iH%2FZ6jrbODlN1%2FbHnIB1WS8lDPlF%2F1IGX7mDdPoAA%3D&reserved=0> Connects TR bundle with OBIO<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGEOS-ESM%2FGEOSgcm_GridComp%2Fblob%2Fb5ab7e3ad1d73c0513aae9593b79e7e55b94f64c%2FGEOSogcm_GridComp%2FGEOS_OgcmGridComp.F90%23L1297-L1309&data=05%7C01%7Cmichael.f.mehari%40nasa.gov%7C5cc86d1dd68c4f31758b08daf272660f%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638088870396166760%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vge1wtXA1s4zX2x87E%2FbZ6xLXRhbFemU9me%2BLNC2WfY%3D&reserved=0>
  *   GEOS_OceanGridComp.F90<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGEOS-ESM%2FGEOS_OceanGridComp%2Fblob%2Fdevelop%2FGEOS_OceanGridComp.F90&data=05%7C01%7Cmichael.f.mehari%40nasa.gov%7C5cc86d1dd68c4f31758b08daf272660f%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638088870396166760%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=t3vJjjDjqS9KtnQ1F1wxkWqICrkmS03cPqmWJmnv8Kg%3D&reserved=0>
TR and TRFLUX are imported to MOM (=MOM5) https://github.com/GEOS-ESM/GEOS_OceanGridComp/blob/f69b49a13261af0f3c469af287f7309fdc8ee627/GEOS_Ocean_StateSpecs.rc#L21-L22<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGEOS-ESM%2FGEOS_OceanGridComp%2Fblob%2Ff69b49a13261af0f3c469af287f7309fdc8ee627%2FGEOS_Ocean_StateSpecs.rc%23L21-L22&data=05%7C01%7Cmichael.f.mehari%40nasa.gov%7C5cc86d1dd68c4f31758b08daf272660f%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638088870396166760%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WVsZGsdqYGL31RYV29CmSkw%2FEmXh7MazCIIp5wvxAOM%3D&reserved=0>

@mfmehari<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmfmehari&data=05%7C01%7Cmichael.f.mehari%40nasa.gov%7C5cc86d1dd68c4f31758b08daf272660f%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638088870396791623%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Yg2lWqgsI%2B8biXs9ZWR%2F0CR6IKbLoTgUKyYqIn8%2FyEQ%3D&reserved=0>: What is TRFLUX? See ⬇️

  *   MOM_GEOS5PlugMod.F90<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGEOS-ESM%2FGEOS_OceanGridComp%2Fblob%2Fdevelop%2FMOM_GEOS5PlugMod%2FMOM_GEOS5PlugMod.F90&data=05%7C01%7Cmichael.f.mehari%40nasa.gov%7C5cc86d1dd68c4f31758b08daf272660f%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638088870396791623%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jhGJdRYBws7gwOI9qVhGQdWK%2FRs4OCOsCB9MVYg63aw%3D&reserved=0> Declare TR as Import
     *   https://github.com/GEOS-ESM/GEOS_OceanGridComp/blob/f69b49a13261af0f3c469af287f7309fdc8ee627/MOM_GEOS5PlugMod/MOM_GEOS5PlugMod_StateSpecs.rc#L32<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGEOS-ESM%2FGEOS_OceanGridComp%2Fblob%2Ff69b49a13261af0f3c469af287f7309fdc8ee627%2FMOM_GEOS5PlugMod%2FMOM_GEOS5PlugMod_StateSpecs.rc%23L32&data=05%7C01%7Cmichael.f.mehari%40nasa.gov%7C5cc86d1dd68c4f31758b08daf272660f%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638088870396791623%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FyOBA65sZVfSFL5MhtE4RS8if%2F9ntIPXLG9rB6rr9wk%3D&reserved=0>
     *   https://github.com/GEOS-ESM/GEOS_OceanGridComp/blob/f69b49a13261af0f3c469af287f7309fdc8ee627/MOM_GEOS5PlugMod/MOM_GEOS5PlugMod.F90#L645<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGEOS-ESM%2FGEOS_OceanGridComp%2Fblob%2Ff69b49a13261af0f3c469af287f7309fdc8ee627%2FMOM_GEOS5PlugMod%2FMOM_GEOS5PlugMod.F90%23L645&data=05%7C01%7Cmichael.f.mehari%40nasa.gov%7C5cc86d1dd68c4f31758b08daf272660f%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638088870396791623%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=X6CB8uSvunj0vWlOAkB3MF4%2F6VLJGFS5EHGlHG82Iws%3D&reserved=0>
     *   https://github.com/GEOS-ESM/GEOS_OceanGridComp/blob/f69b49a13261af0f3c469af287f7309fdc8ee627/MOM_GEOS5PlugMod/MOM_GEOS5PlugMod.F90#L695-L698<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGEOS-ESM%2FGEOS_OceanGridComp%2Fblob%2Ff69b49a13261af0f3c469af287f7309fdc8ee627%2FMOM_GEOS5PlugMod%2FMOM_GEOS5PlugMod.F90%23L695-L698&data=05%7C01%7Cmichael.f.mehari%40nasa.gov%7C5cc86d1dd68c4f31758b08daf272660f%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638088870396791623%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6UzNhG6AEzy3CQs3uMU0SRNZGMHzSg48LPdevpZd%2Frc%3D&reserved=0>
     *   Get TR from bundle, _put_ it in MOM's state: https://github.com/GEOS-ESM/GEOS_OceanGridComp/blob/f69b49a13261af0f3c469af287f7309fdc8ee627/MOM_GEOS5PlugMod/MOM_GEOS5PlugMod.F90#L919-L942<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGEOS-ESM%2FGEOS_OceanGridComp%2Fblob%2Ff69b49a13261af0f3c469af287f7309fdc8ee627%2FMOM_GEOS5PlugMod%2FMOM_GEOS5PlugMod.F90%23L919-L942&data=05%7C01%7Cmichael.f.mehari%40nasa.gov%7C5cc86d1dd68c4f31758b08daf272660f%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638088870396791623%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cH4AGiw3To%2FvKqFG8NQwWeQiD5vNrK5Lv0ueRGp7mro%3D&reserved=0>
     *   Get TR from bundle, _get_ it from MOM's state: https://github.com/GEOS-ESM/GEOS_OceanGridComp/blob/f69b49a13261af0f3c469af287f7309fdc8ee627/MOM_GEOS5PlugMod/MOM_GEOS5PlugMod.F90#L950-L971<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGEOS-ESM%2FGEOS_OceanGridComp%2Fblob%2Ff69b49a13261af0f3c469af287f7309fdc8ee627%2FMOM_GEOS5PlugMod%2FMOM_GEOS5PlugMod.F90%23L950-L971&data=05%7C01%7Cmichael.f.mehari%40nasa.gov%7C5cc86d1dd68c4f31758b08daf272660f%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638088870396791623%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LWUFZ7W7SaiquhQAeuGmWRdHaMkxcnwF6mlnJesQR7I%3D&reserved=0>
  *   In MOM5 work with: https://github.com/GEOS-ESM/GEOS_OceanGridComp/blob/f69b49a13261af0f3c469af287f7309fdc8ee627/MOM_GEOS5PlugMod/MOM_GEOS5PlugMod.F90#L64-L65<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGEOS-ESM%2FGEOS_OceanGridComp%2Fblob%2Ff69b49a13261af0f3c469af287f7309fdc8ee627%2FMOM_GEOS5PlugMod%2FMOM_GEOS5PlugMod.F90%23L64-L65&data=05%7C01%7Cmichael.f.mehari%40nasa.gov%7C5cc86d1dd68c4f31758b08daf272660f%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638088870396791623%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pmsZVE6wBlKLedg%2BPRsxqWvK8Xbg3f2NPUmV%2B9nhPPo%3D&reserved=0> that are accessed from ocean_model.F90<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGEOS-ESM%2FMOM5%2Fblob%2Fd5fb80f42f915a8bddba71f9c1315a6e05c03b95%2Fsrc%2Fmom5%2Focean_core%2Focean_model.F90%23L572-L576&data=05%7C01%7Cmichael.f.mehari%40nasa.gov%7C5cc86d1dd68c4f31758b08daf272660f%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638088870396947842%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0c3%2FQ1RNjokTW56cNtcFi2YHwQjA55f6OgEGFNcp4Vs%3D&reserved=0>

@mfmehari<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmfmehari&data=05%7C01%7Cmichael.f.mehari%40nasa.gov%7C5cc86d1dd68c4f31758b08daf272660f%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638088870396947842%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4cmObS%2BlNWQ1Z76ihU2F%2Bs5735AZuYtVp7r04OP8nIU%3D&reserved=0>: Why only TR shows up, where is TRFLUX?

**Comment by sanAkel** [comment]
> Hi Santha, I have been working with the CVS S2Sv3 model (with OBIO on). I don’t see the import TRFLUX used in this model. It is commented out in /discover/nobackup/mmehari/yuri-s2s3/GEOSodas/src/GEOSgcs_GridComp/GEOSgcm_GridComp/GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/GuestOcean_GridComp.F90 Thank you, Michael 

Thanks! @mfmehari

Are you able to build and run MOM5 coupled model from https://github.com/GEOS-ESM/GEOSgcm? There are instructions in [wiki page](https://github.com/GEOS-ESM/GEOSgcm/wiki) if you need. I would like to be **sure** that taking `TRFLUX` does not cause any problem. Thanks again.

**Comment by sanAkel** [comment]
> For OBIO to work in the Git model, it will need to be updated as in the CVS model. 
I can rerun it (without OBIO) using the latest version; please let me know if that is what you wanted.
Thank you,
Michael

I'll look for you via MS Teams ...

**Comment by yvikhlya** [comment]
> Why only TR shows up, where is TRFLUX?

This would be a question for Cecile. What ever tracers obio model needs to advect(diffuse) through ocean model mechanics, ocean model should be able to do.

**Comment by sanAkel** [comment]
> > Why only TR shows up, where is TRFLUX?
> 
> This would be a question for Cecile. What ever tracers obio model needs to advect(diffuse) through ocean model mechanics, ocean model should be able to do.

👍 @mfmehari can you check with Cecile and confirm what @yvikhlya asked.

**Comment by mfmehari** [comment]
Will do, thanks.

**Comment by mfmehari** [comment]
Cecile said that she has no recollection of TRFLUX in OBIO. We looked at the OBIO codes, including in the old Fortuna version (where OBIO was working), and there is no such export bundle from OBIO, even though it is mentioned in the import specification statements in the Ocean GCs. The OBIO tracer fields currently are only bundled in the TR bundle and exported to the Ocean GC.

**Comment by yvikhlya** [comment]
Cecile and Watson may have planned to add TRFLUX some time ago and Max created an interface for them, but it was never added. I guess, it can be removed in this case.

**Comment by sanAkel** [comment]
@mfmehari is this what Cecile said? In other words, is ⬇️ true??

> Cecile and Watson may have planned to add TRFLUX some time ago and Max created an interface for them, but it was never added. I guess, it can be removed in this case.

**Comment by mfmehari** [comment]
I think so. TRFLUX was never used with OBIO even in the old GEOS Fortuna version, unless it was coming from other GCs.

**Comment by sanAkel** [comment]
Thank you @mfmehari and @yvikhlya
