### ISSUE TITLE
A "spec" file for SetServices of GEOS_OceanGridComp.F90

### ISSUE THREAD

**Issue by sanAkel** [GEOS-ESM/GEOS_OceanGridComp#4]
This issue proposes an _enhancement_ in the form of a _clean_ _up_ of the **long** `SetServices` in https://github.com/GEOS-ESM/GEOS_OceanGridComp/blob/develop/GEOS_OceanGridComp.F90

The list of imports, exports and (one) internal variable is: https://github.com/GEOS-ESM/GEOS_OceanGridComp/blob/2ae923b8650e10cb0d45205d76bfc3e7a3b9c41c/GEOS_OceanGridComp.F90#L148-L603
**Note**: 
Few fields are _conditional_ to `MOM` (=MOM5), `DO_DATASEA` and `DUAL_OCEAN`; strictly speaking `DUAL_OCEAN` must be _nested_ within `MOM.`  I intend to _package_ all `DUAL_OCEAN` logic into a subroutine in a later issue.

For testing this change, please set up a coupled model experiment using `gcm_setup` and let myself and/or @mathomp4 know so we can supply a set of restarts. The recommended set up is `C12 x 5deg` (atmosphere x ocean resolutions). This change should **not** change answers.

If there are any questions, please reach out. Thanks!

**Comment by darianboggs** [comment]
Pull request created

**Comment by sanAkel** [comment]
https://github.com/GEOS-ESM/GEOS_OceanGridComp/pull/6 closes it.
