### ISSUE TITLE
WMMA (GEOSwgcm)

### ISSUE THREAD

**Issue by adarmenov** [GEOS-ESM/GEOS_OceanGridComp#53]
WIP.

**Comment by sanAkel** [comment]
@adarmenov It would be best to have the wave component as a separate repository and not reside _here_. Please see [this issue](https://github.com/GEOS-ESM/GEOS_OceanGridComp/issues/29). It did not any support from all parties, but I expect you to appreciate the goodness of keeping things self-contained! Thanks!

I'm sure @mathomp4 and @tclune will be wiling make a new fixture/repo for the `GEOSwgcm`.
