### ISSUE TITLE
Daily collections for high resolutions

### ISSUE THREAD

**Issue by yvikhlya** [GEOS-ESM/GEOS_OceanGridComp#62]
Is there any reason for making daily output for high resolutions by default, like
```
"prog_z",    1,"days",1,"days","Time",
```
? These daily files are huge and I would suggest to change the default output to monthly for 0.25 and 0.66 degree configurations.

**Comment by sanAkel** [comment]
At some stage we decided to have these because we could not write monthlies. Either perpetual year or time was messed up. Anyway the `user` can have what they want- should be removed.

**Comment by yvikhlya** [comment]
Perpetual year is still messed up (not sure when it is going to be fixed), but this is regardless if output is monthly or daily. We can do perpetual runs, and we can write monthlies, but MOM collections miss the last month (last day) of the year in perpetual mode. This suggestion is for convenience, since we run long runs with high resolutions more often than short runs. If nobody else is interested, we can leave it as it is.

**Comment by sanAkel** [comment]
> Perpetual year is still messed up (not sure when it is going to be fixed), but this is regardless if output is monthly or daily. We can do perpetual runs, and we can write monthlies, but MOM collections miss the last month (last day) of the year in perpetual mode. This suggestion is for convenience, since we run long runs with high resolutions more often than short runs. If nobody else is interested, we can leave it as it is. 

Your suggestion is good. Please see PR
