### ISSUE TITLE
Crash with 'FATAL from PE     0: MOM_obsolete_params'

### ISSUE THREAD

**Issue by zhaobin74** [GEOS-ESM/GEOS_OceanGridComp#77]
Coupled run with MOM6 at 1440x1080 resolution crashed in MOM6 initializer:
```
WARNING from PE     0: MOM_obsolete_params: ETA_TOLERANCE_AUX is an obsolete run-time flag.


WARNING from PE     0: MOM_obsolete_params: ETA_TOLERANCE_AUX is an obsolete run-time flag.


WARNING from PE     0: MOM_file_parser : DEFAULT_2018_ANSWERS over-ridden.  Line: 'DEFAULT_2018_ANSWERS = False' in file MOM_override.


WARNING from PE     0: MOM_file_parser : DEFAULT_2018_ANSWERS over-ridden.  Line: 'DEFAULT_2018_ANSWERS = False' in file MOM_override.


FATAL from PE     0: MOM_obsolete_params: DEFAULT_2018_ANSWERS is an obsolete run-time flag, and should not be used. Instead use DEFAULT_ANSWER_DATE.


FATAL from PE     0: MOM_obsolete_params: DEFAULT_2018_ANSWERS is an obsolete run-time flag, and should not be used. Instead use DEFAULT_ANSWER_DATE.

--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on

``` 

```DEFAULT_2018_ANSWERS``` is not being accepted, but present in both ```MOM_input``` and ```MOM_override```.
It should be commented out or removed from both config files.

GEOS version: 11.6.0

**Comment by mathomp4** [comment]
@zhaobin74 Can you look at #78. I just sort of went in and removed any line like that.

*NOTE*: #79 is aimed to GEOSgcm v12, so you'll want to try #78 which is for GEOSgcm v11

**Comment by sanAkel** [comment]
@mathomp4, @zhaobin74 the _fix_ is simple! Just set a `date` for `DEFAULT_ANSWER_DATE`. See this [example.](https://github.com/NOAA-GFDL/MOM6-examples/blob/433917f9ee529a3b331dcd2bb0d358f51256d6d6/ice_ocean_SIS2/OM4_025/MOM_parameter_doc.all#L159-L160)
